version: '3.7'
services:
    service_1:
        build: ./service_1
        ports:
        - target: 5000
          published: 5000
          protocol: tcp
        environment:
            SFIA2_PROJECT_DB_URI: ${SFIA2_PROJECT_DB_URI}
            SECRET_KEY: ${SECRET_KEY}
        depends_on: 
          service_4
    service_2:
        build: ./service_2
        ports:
        - target: 5000
          published: 5001
          protocol: tcp
    service_3:
        build: ./service_3
        ports:
        - target: 5000
          published: 5002
          protocol: tcp
    service_4:
        build: ./service_4
        ports:
        - target: 5000
          published: 5003
          protocol: tcp
        depends_on: 
          - service_2
          - service_3 

